; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=powerpc-unknown-linux-gnu -o - %s | FileCheck %s
; RUN: llc -mtriple=powerpc64-unknown-linux-gnu -o - %s | FileCheck %s --check-prefix=CHECK-PPC64
; RUN: llc -mtriple=powerpc-unknown-linux-gnu -mattr=+booke -o - %s | FileCheck %s --check-prefix=CHECK-BOOKE

; Test that interrupt handlers save LR, CR, and emit RFI instead of BLR

define void @test_generic_interrupt() #0 {
; CHECK-LABEL: test_generic_interrupt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mflr 0
; CHECK-NEXT:    stw 0, 4(1)
; CHECK:        mfcr
; CHECK-NEXT:    stw
; CHECK:        blr
; CHECK-NEXT:    lwz
; CHECK-NEXT:    mtlr
; CHECK-NEXT:    rfi

; CHECK-PPC64-LABEL: test_generic_interrupt:
; CHECK-PPC64:       # %bb.0:
; CHECK-PPC64-NEXT:    mflr 0
; CHECK-PPC64-NEXT:    std 0, 16(1)
; CHECK-PPC64:        mfcr
; CHECK-PPC64-NEXT:    std
; CHECK-PPC64:        blr
; CHECK-PPC64-NEXT:    ld
; CHECK-PPC64-NEXT:    mtlr
; CHECK-PPC64-NEXT:    rfi

; CHECK-BOOKE-LABEL: test_generic_interrupt:
; CHECK-BOOKE:       # %bb.0:
; CHECK-BOOKE-NEXT:    mflr 0
; CHECK-BOOKE:        mfcr
; CHECK-BOOKE:        blr
; CHECK-BOOKE:        mtlr
; CHECK-BOOKE-NEXT:    rfi

  ret void
}

; Test that interrupt handlers that make calls save all used registers
declare void @external_function()

define void @test_interrupt_with_call() #0 {
; CHECK-LABEL: test_interrupt_with_call:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mflr 0
; CHECK-NEXT:    stw 0, 4(1)
; CHECK:        mfcr
; CHECK:        bl external_function
; CHECK:        blr
; CHECK:        mtlr
; CHECK-NEXT:    rfi

; CHECK-PPC64-LABEL: test_interrupt_with_call:
; CHECK-PPC64:       # %bb.0:
; CHECK-PPC64-NEXT:    mflr 0
; CHECK-PPC64-NEXT:    std 0, 16(1)
; CHECK-PPC64:        mfcr
; CHECK-PPC64:        bl external_function
; CHECK-PPC64:        blr
; CHECK-PPC64:        mtlr
; CHECK-PPC64-NEXT:    rfi

; CHECK-BOOKE-LABEL: test_interrupt_with_call:
; CHECK-BOOKE:       # %bb.0:
; CHECK-BOOKE-NEXT:    mflr 0
; CHECK-BOOKE:        mfcr
; CHECK-BOOKE:        bl external_function
; CHECK-BOOKE:        blr
; CHECK-BOOKE:        mtlr
; CHECK-BOOKE-NEXT:    rfi

  call void @external_function()
  ret void
}

; Test critical interrupt type
define void @test_critical_interrupt() #1 {
; CHECK-LABEL: test_critical_interrupt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mflr 0
; CHECK:        mfcr
; CHECK:        blr
; CHECK:        mtlr
; CHECK-NEXT:    rfi

; CHECK-PPC64-LABEL: test_critical_interrupt:
; CHECK-PPC64:       # %bb.0:
; CHECK-PPC64-NEXT:    mflr 0
; CHECK-PPC64:        mfcr
; CHECK-PPC64:        blr
; CHECK-PPC64:        mtlr
; CHECK-PPC64-NEXT:    rfi

; CHECK-BOOKE-LABEL: test_critical_interrupt:
; CHECK-BOOKE:       # %bb.0:
; CHECK-BOOKE-NEXT:    mflr 0
; CHECK-BOOKE:        mfcr
; CHECK-BOOKE:        blr
; CHECK-BOOKE:        mtlr
; CHECK-BOOKE-NEXT:    rfi

  ret void
}

; Test external interrupt type
define void @test_external_interrupt() #2 {
; CHECK-LABEL: test_external_interrupt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mflr 0
; CHECK:        mfcr
; CHECK:        blr
; CHECK:        mtlr
; CHECK-NEXT:    rfi

; CHECK-PPC64-LABEL: test_external_interrupt:
; CHECK-PPC64:       # %bb.0:
; CHECK-PPC64-NEXT:    mflr 0
; CHECK-PPC64:        mfcr
; CHECK-PPC64:        blr
; CHECK-PPC64:        mtlr
; CHECK-PPC64-NEXT:    rfi

; CHECK-BOOKE-LABEL: test_external_interrupt:
; CHECK-BOOKE:       # %bb.0:
; CHECK-BOOKE-NEXT:    mflr 0
; CHECK-BOOKE:        mfcr
; CHECK-BOOKE:        blr
; CHECK-BOOKE:        mtlr
; CHECK-BOOKE-NEXT:    rfi

  ret void
}

attributes #0 = { nounwind "interrupt" }
attributes #1 = { nounwind "interrupt"="critical" }
attributes #2 = { nounwind "interrupt"="external" }

