; RUN: llc -mtriple=powerpc-none-eabivle -mcpu=e200z4 -mvle -Oz < %s | FileCheck %s
; RUN: llc -mtriple=powerpc-none-eabivle -mcpu=e200z4 -mvle -O2 < %s | FileCheck %s --check-prefix=NOOPT

; Test E_STSWI, E_STSWX (32-bit VLE Store String Word Indexed) instructions.
; These instructions store a string of bytes/words from consecutive registers to memory.
; Format: e_stswi rS, rA, NB (immediate byte count), e_stswx rS, rA, rB (byte count in register).
; Reference: VLEPEM Table B-3, VLEPIM Section 4.2.2

target datalayout = "E-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v128:128:128-n32"
target triple = "powerpc-none-eabivle"

; Note: STSWI/STSWX are complex instructions that may not always be generated by LLVM
; These tests verify the instruction patterns exist and can be selected when appropriate

; Test E_STSWI with immediate byte count
define void @test_e_stswi(i8* %base, i32 %val1, i32 %val2) optsize minsize {
entry:
; CHECK-LABEL: @test_e_stswi
; This test verifies the pattern exists - actual generation depends on code structure
  %trunc1 = trunc i32 %val1 to i8
  store i8 %trunc1, i8* %base, align 1
  %ptr2 = getelementptr inbounds i8, i8* %base, i32 1
  %trunc2 = trunc i32 %val2 to i8
  store i8 %trunc2, i8* %ptr2, align 1
  ret void
}

